[package]
name = "chessica-engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chessica = { path = "../chessica" }
log = "0.4.17"
simplelog = "0.12.1"
test-case = "3.1.0"
